import type { EraTag, FeelTag, StandardForm, TempoFeel } from '@/types/database'

export interface SeedStandard {
  title: string
  composer: string[]
  year_composed: number | null
  original_key: string | null
  time_signature: string
  tempo_feel: TempoFeel | null
  form: StandardForm | null
  era_tags: EraTag[]
  feel_tags: FeelTag[]
  factoid: string | null
  is_official: boolean
  status: 'official'
}

export const standards: SeedStandard[] = [
  // ── Great American Songbook ─────────────────────────────────────────────────
  {
    title: 'Autumn Leaves',
    composer: ['Joseph Kosma'],
    year_composed: 1945,
    original_key: 'G minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Originally a French chanson called "Les feuilles mortes," with lyrics by poet Jacques Prévert. Miles Davis\'s 1958 Cannonball Adderley session recording is one of the most famous jazz versions.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'All The Things You Are',
    composer: ['Jerome Kern'],
    year_composed: 1939,
    original_key: 'Ab major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From the musical "Very Warm for May," this tune cycles through multiple key centers and has become one of the most harmonically rich standards in the jazz repertoire. Charlie Parker loved to improvise over its changes.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Body And Soul',
    composer: ['Johnny Green'],
    year_composed: 1930,
    original_key: 'Db major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Coleman Hawkins\'s 1939 recording is widely considered the first great jazz improvisation on record — he barely plays the melody, instead spinning entirely original lines over the changes.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Misty',
    composer: ['Erroll Garner'],
    year_composed: 1954,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Erroll Garner composed this while on a flight from Chicago, reportedly writing it in his head without an instrument since he couldn\'t read music. Johnny Mathis\'s 1959 vocal version made it a pop hit.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Summertime',
    composer: ['George Gershwin'],
    year_composed: 1935,
    original_key: 'A minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'From the opera "Porgy and Bess," this lullaby has been recorded more than any other American song in history — over 33,000 versions documented. Miles Davis\'s 1958 version reimagines it as a cool modal piece.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Take The A Train',
    composer: ['Billy Strayhorn'],
    year_composed: 1941,
    original_key: 'C major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook', 'swing'],
    feel_tags: [],
    factoid: 'Duke Ellington\'s signature theme, written by his collaborator Billy Strayhorn. The title refers to the A subway line to Harlem. Strayhorn reportedly wrote it after Ellington gave him directions to his apartment.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Star Dust',
    composer: ['Hoagy Carmichael'],
    year_composed: 1927,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'One of the most recorded songs in history, originally written as a fast piano rag. Mitchell Parish added the lyrics in 1929 and it became a slow ballad — the version we know today.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'My Funny Valentine',
    composer: ['Richard Rodgers'],
    year_composed: 1937,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'From the musical "Babes in Arms," the song\'s descending bass line over a static chord has inspired countless jazz versions. Miles Davis\'s live 1964 version with the Wayne Shorter Quintet is legendary.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'The Girl From Ipanema',
    composer: ['Antônio Carlos Jobim', 'Vinícius de Moraes'],
    year_composed: 1962,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['bossa-nova'],
    factoid: 'Inspired by a real teenager named Helô Pinheiro who walked past a bar in Rio where Jobim and de Moraes sat. The recording featuring Astrud Gilberto and Stan Getz became a worldwide hit in 1964.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'How High The Moon',
    composer: ['Morgan Lewis'],
    year_composed: 1940,
    original_key: 'G major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From the Broadway musical "Two for the Show." The chord changes are famous as the basis for Charlie Parker\'s "Ornithology" — beboppers would play the new melody over the original\'s changes.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'On Green Dolphin Street',
    composer: ['Bronisław Kaper'],
    year_composed: 1947,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Written for a 1947 film of the same name, this tune sat obscure for a decade until Miles Davis recorded a landmark version in 1958, turning it into one of the most-played jazz standards.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Night And Day',
    composer: ['Cole Porter'],
    year_composed: 1932,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Cole Porter\'s most covered song, originally written for Fred Astaire. The melody\'s insistent repeated note (a tritone away from the key) was considered daring for its era.',
    is_official: true,
    status: 'official',
  },
  {
    title: "There Will Never Be Another You",
    composer: ['Harry Warren'],
    year_composed: 1942,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Written for the film "Iceland," this 32-bar AABA tune is a jazz jam session staple. Its straightforward but sophisticated chord changes make it a go-to vehicle for improvisers at all levels.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Stella By Starlight',
    composer: ['Victor Young'],
    year_composed: 1944,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Written for the 1944 film "The Uninvited," the haunting through-composed melody cycles through many keys. Miles Davis\'s 1958 recording set the template most jazz musicians follow today.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Just Friends',
    composer: ['John Klenner'],
    year_composed: 1931,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'A swing-era pop song that became a bebop favorite. Charlie Parker\'s 1949 recording with strings is one of his most beautiful — he plays the melody with aching tenderness before launching into improvisation.',
    is_official: true,
    status: 'official',
  },
  {
    title: "I'll Remember April",
    composer: ['Gene de Paul', 'Don Raye'],
    year_composed: 1941,
    original_key: 'G major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From the 1942 film "Ride \'Em Cowboy," this tune\'s shift from G major to G minor in the bridge has made it a beloved vehicle for jazz improvisers, particularly at burning tempos.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Bye Bye Blackbird',
    composer: ['Ray Henderson'],
    year_composed: 1926,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'A Tin Pan Alley song that became a jazz standard when Miles Davis recorded his definitive version in 1956. John Coltrane and Bill Evans are both on that recording, making it a document of a particular moment in jazz history.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'The Nearness Of You',
    composer: ['Hoagy Carmichael'],
    year_composed: 1937,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Originally written for a film but cut from the final release, the song found its audience through recordings. Norah Jones\'s 2002 recording introduced it to a whole new generation.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'The Days Of Wine And Roses',
    composer: ['Henry Mancini'],
    year_composed: 1962,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Written for the Blake Edwards film of the same name, the song won the Academy Award for Best Original Song. Tony Bennett and Bill Evans\'s duo recording is considered one of the greatest jazz vocal albums ever made.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'My Romance',
    composer: ['Richard Rodgers'],
    year_composed: 1935,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'From the musical "Jumbo," this gorgeous ballad is notable for having no verse and no blue notes — it\'s a pure, consonant melody. Bill Evans\'s solo piano interpretation is considered definitive.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Beautiful Love',
    composer: ['Victor Young'],
    year_composed: 1931,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'A minor-key standard popular at jam sessions for its straightforward but elegant changes. Chet Baker\'s lyrical interpretations helped cement it as a jazz staple.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Lush Life',
    composer: ['Billy Strayhorn'],
    year_composed: 1938,
    original_key: 'Db major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook', 'swing'],
    feel_tags: ['ballad'],
    factoid: 'Billy Strayhorn began writing this at age 16. The song\'s sprawling, through-composed form and sophisticated harmony make it one of the most challenging standards to master — most artists record it once and never again.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Come Rain Or Come Shine',
    composer: ['Harold Arlen'],
    year_composed: 1946,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'From the musical "St. Louis Woman," Harold Arlen\'s bluesy melody spans a full thirteenth — an unusually wide range. Ray Charles\'s recording is the emotional standard against which all others are measured.',
    is_official: true,
    status: 'official',
  },
  {
    title: "You Don't Know What Love Is",
    composer: ['Gene de Paul'],
    year_composed: 1941,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Written for the Abbott and Costello film "Keep \'Em Flying." Chet Baker\'s fragile, intimate treatment turned it into a signature piece and an archetype of jazz vulnerability.',
    is_official: true,
    status: 'official',
  },
  {
    title: "Don't Get Around Much Anymore",
    composer: ['Duke Ellington'],
    year_composed: 1940,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook', 'swing'],
    feel_tags: [],
    factoid: 'Originally an instrumental called "Never No Lament," lyricist Bob Russell added the now-famous words in 1942. Ellington\'s original had a more somber feel; the lyrics gave it a wistful, swinging character.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Tenderly',
    composer: ['Walter Gross'],
    year_composed: 1946,
    original_key: 'Eb major',
    time_signature: '3/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'A waltz that became Rosemary Clooney\'s signature. Its lilting 3/4 time and romantic melody made it an unlikely jazz standard, but its warm harmonic language invites beautiful improvisation.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Skylark',
    composer: ['Hoagy Carmichael'],
    year_composed: 1941,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Carmichael\'s melody was inspired by hearing a blackbird sing. Johnny Mercer\'s poetic lyrics are considered among the finest in American popular song, and the bridge modulation is a master class in harmonic surprise.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Fly Me To The Moon',
    composer: ['Bart Howard'],
    year_composed: 1954,
    original_key: 'A minor',
    time_signature: '3/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'Originally titled "In Other Words," it was Frank Sinatra\'s recording — renamed "Fly Me to the Moon" — that became iconic. NASA astronauts reportedly played it during the Apollo missions.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Lover Man',
    composer: ['Jimmy Davis', 'Roger Ramirez', 'Jimmy Sherman'],
    year_composed: 1941,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Billie Holiday recorded this in 1944 while seriously ill — she could barely stand and gave a fragmented, haunted performance that many consider her most emotionally raw recording.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Have You Met Miss Jones',
    composer: ['Richard Rodgers'],
    year_composed: 1937,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'The bridge of this Rodgers & Hart tune is harmonically adventurous — a series of third-related key changes that anticipate bebop. It was likely an influence on John Coltrane\'s "Giant Steps" concept.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Speak Low',
    composer: ['Kurt Weill'],
    year_composed: 1943,
    original_key: 'G minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From the musical "One Touch of Venus" with lyrics by Ogden Nash. Kurt Weill\'s European sensibility gives the tune an unusual, chromatic quality that sets it apart from typical American standards.',
    is_official: true,
    status: 'official',
  },

  // ── Swing ──────────────────────────────────────────────────────────────────
  {
    title: "Cherokee",
    composer: ['Ray Noble'],
    year_composed: 1938,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['swing', 'bebop'],
    feel_tags: [],
    factoid: 'The demanding bridge — a rapid-fire series of ii-V-I progressions through distant keys — is what made this tune a bebop proving ground. Charlie Parker\'s ability to navigate the bridge helped establish his genius.',
    is_official: true,
    status: 'official',
  },
  {
    title: "It Don't Mean A Thing (If It Ain't Got That Swing)",
    composer: ['Duke Ellington'],
    year_composed: 1932,
    original_key: 'G minor',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['swing', 'great-american-songbook'],
    feel_tags: [],
    factoid: 'Ellington\'s manifesto on swing predates the Swing Era by several years. Ivie Anderson\'s original vocal scat solo set a template for jazz singing. The title became a defining phrase of the era.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'In A Mellotone',
    composer: ['Duke Ellington'],
    year_composed: 1940,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['swing'],
    feel_tags: [],
    factoid: 'Based on the chord changes of "Rose Room," Ellington\'s melody flows effortlessly over the classic progression. The tune became a jam session favorite because the changes are so comfortable for improvisation.',
    is_official: true,
    status: 'official',
  },

  // ── Bebop ──────────────────────────────────────────────────────────────────
  {
    title: "'Round Midnight",
    composer: ['Thelonious Monk'],
    year_composed: 1944,
    original_key: 'Eb minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['bebop'],
    feel_tags: ['ballad'],
    factoid: 'Monk composed this at around 17 years old, making it one of the earliest bebop compositions. Miles Davis\'s 1957 Columbia recording — his first for a major label — made the tune internationally famous.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Confirmation',
    composer: ['Charlie Parker'],
    year_composed: 1946,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'One of Parker\'s most sophisticated originals — a 32-bar melody that outlines the underlying harmony in perfect counterpoint. The tune was reportedly written fully formed, as if Bird just "heard" it.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Donna Lee',
    composer: ['Charlie Parker'],
    year_composed: 1947,
    original_key: 'Ab major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Though credited to Miles Davis on the original recording, Parker is now generally considered the composer. The melody\'s rapid chromatic motion over "Indiana" changes makes it one of the most demanding heads in the repertoire.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Ornithology',
    composer: ['Charlie Parker', 'Benny Harris'],
    year_composed: 1945,
    original_key: 'G major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'A bebop contrafact written over the changes of "How High the Moon." The title refers to Bird\'s nickname — "Yardbird" or just "Bird." Parker\'s nickname itself came from his love of chicken (yard birds).',
    is_official: true,
    status: 'official',
  },
  {
    title: 'A Night In Tunisia',
    composer: ['Dizzy Gillespie'],
    year_composed: 1942,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['bebop'],
    feel_tags: ['latin', 'afro-cuban'],
    factoid: 'One of the first jazz compositions to incorporate Afro-Cuban rhythms. The dramatic interlude before the solos — where the rhythm section drops out for two bars — is one of the most iconic moments in jazz.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Groovin\' High',
    composer: ['Dizzy Gillespie'],
    year_composed: 1945,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Written over the changes of "Whispering," this Gillespie tune from the first bebop recording sessions features one of the great saxophone-trumpet unison heads. The 1945 recording with Charlie Parker is essential listening.',
    is_official: true,
    status: 'official',
  },
  {
    title: "Well You Needn't",
    composer: ['Thelonious Monk'],
    year_composed: 1944,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Monk\'s bluesy, angular melody uses "wrong" notes that are somehow perfectly right. The tune\'s punchy, percussive rhythm influenced an entire generation of pianists to think about rhythm in melody.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Epistrophy',
    composer: ['Thelonious Monk', 'Kenny Clarke'],
    year_composed: 1942,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Monk\'s closing theme at the Five Spot Café, where he held a legendary residency in 1957. The chromatic side-slipping in the melody was so unusual that musicians initially dismissed Monk as unable to play — they were wrong.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Straight, No Chaser',
    composer: ['Thelonious Monk'],
    year_composed: 1951,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['bebop', 'hard-bop'],
    feel_tags: [],
    factoid: 'A 12-bar blues with a melody so angular and unexpected it sounds like the notes are placed in the wrong bars — until you realize Monk\'s displaced phrasing is the entire point. One of the most deceptively simple heads to play correctly.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'In Walked Bud',
    composer: ['Thelonious Monk'],
    year_composed: 1948,
    original_key: 'Bb minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Written as a tribute to pianist Bud Powell, Monk\'s friend and fellow bebop innovator. The minor key vamp and stark melody reflect the dark, troubled side of Powell\'s genius.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Bemsha Swing',
    composer: ['Thelonious Monk', 'Denzil Best'],
    year_composed: 1952,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Co-written with drummer Denzil Best, the title "Bemsha" has no clear meaning — some think it\'s a portmanteau of the co-writers\' names. The rhythm feel was a direct influence on later "second line" jazz approaches.',
    is_official: true,
    status: 'official',
  },

  // ── Blues ───────────────────────────────────────────────────────────────────
  {
    title: "Billie's Bounce",
    composer: ['Charlie Parker'],
    year_composed: 1945,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Named after Parker\'s booking agent Billy Shaw (spelled as Billie in the original title), this bebop blues was recorded at Parker\'s very first studio session as a leader. Five different takes survive, all essential listening.',
    is_official: true,
    status: 'official',
  },
  {
    title: "Now's The Time",
    composer: ['Charlie Parker'],
    year_composed: 1945,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'Recorded in the same session as "Billie\'s Bounce," the riff was later used by Paul Williams for the R&B hit "The Hucklebuck" in 1949 — raising uncomfortable questions about who owed whom royalties.',
    is_official: true,
    status: 'official',
  },
  {
    title: "Bag's Groove",
    composer: ['Milt Jackson'],
    year_composed: 1952,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['hard-bop'],
    feel_tags: [],
    factoid: 'Named after vibraphonist Milt Jackson\'s nickname. The Miles Davis recording featuring both Davis and Thelonious Monk is famous for the tension between them — Monk allegedly refused to comp behind Davis during his solo at Davis\'s request.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Tenor Madness',
    composer: ['Sonny Rollins'],
    year_composed: 1956,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['hard-bop'],
    feel_tags: [],
    factoid: 'The only recorded encounter between Sonny Rollins and John Coltrane, on the title track of this album. They trade fours and then eights on this simple blues, giving listeners a once-in-a-lifetime comparison.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Mr. PC',
    composer: ['John Coltrane'],
    year_composed: 1959,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'blues',
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'Written as a tribute to bassist Paul Chambers ("PC"), a member of Coltrane\'s rhythm section. The minor blues form and driving tempo have made it a perennial favorite at jam sessions worldwide.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Freddie Freeloader',
    composer: ['Miles Davis'],
    year_composed: 1959,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['cool', 'hard-bop'],
    feel_tags: [],
    factoid: 'From "Kind of Blue," this blues features Wynton Kelly instead of Bill Evans on piano — Kelly\'s more bluesy, gospel-inflected style was a perfect fit for the funky groove. Kelly only appears on this one track from the album.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Watermelon Man',
    composer: ['Herbie Hancock'],
    year_composed: 1962,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['hard-bop'],
    feel_tags: ['funk'],
    factoid: 'Hancock\'s debut album opener became a surprise R&B hit when Mongo Santamaría covered it in 1963. Hancock himself later reimagined it completely for his 1973 "Head Hunters" album, with an Afro-Cuban feel built from breath sounds.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'All Blues',
    composer: ['Miles Davis'],
    year_composed: 1959,
    original_key: 'G major',
    time_signature: '6/8',
    tempo_feel: 'medium',
    form: 'blues',
    era_tags: ['cool', 'modal'],
    feel_tags: [],
    factoid: 'From "Kind of Blue," this blues in 6/8 time has a waltz-like feel that sets it apart from any previous blues recording. The two-bar "riff" horns play between solos became a model for how jazz ensembles interact.',
    is_official: true,
    status: 'official',
  },

  // ── Rhythm Changes ─────────────────────────────────────────────────────────
  {
    title: 'Anthropology',
    composer: ['Charlie Parker', 'Dizzy Gillespie'],
    year_composed: 1945,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'rhythm-changes',
    era_tags: ['bebop'],
    feel_tags: [],
    factoid: 'The definitive bebop take on "I Got Rhythm" changes. Originally titled "Thrivin\' on a Riff," the melody\'s relentless 8th-note barrage became the template for how to write a bebop contrafact.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Oleo',
    composer: ['Sonny Rollins'],
    year_composed: 1954,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'rhythm-changes',
    era_tags: ['hard-bop'],
    feel_tags: [],
    factoid: 'Oleo is a brand name for margarine — Rollins reportedly named it for something mundane he saw in his kitchen. The tune famously opens with 8 bars of melody, then 8 bars of silence (rhythm only), then 8 more bars of melody.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Cottontail',
    composer: ['Duke Ellington'],
    year_composed: 1940,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'rhythm-changes',
    era_tags: ['swing'],
    feel_tags: [],
    factoid: 'Ben Webster\'s tenor solo on the original Ellington big band recording is one of the most celebrated solos in jazz history — earthy, swinging, and endlessly inventive. The tune predates bebop\'s adoption of rhythm changes.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Rhythm-A-Ning',
    composer: ['Thelonious Monk'],
    year_composed: 1957,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'rhythm-changes',
    era_tags: ['bebop', 'hard-bop'],
    feel_tags: [],
    factoid: 'Monk\'s personalization of rhythm changes — the A-section melody uses only three pitches but their rhythmic displacement is so eccentric it took musicians years to figure out the correct phrasing.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'I Got Rhythm',
    composer: ['George Gershwin'],
    year_composed: 1930,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: 'rhythm-changes',
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'The chord progression from this Gershwin tune became so widely used that jazz musicians simply call it "rhythm changes." Hundreds of bebop heads were written over these changes, making it the most reused harmonic template in jazz.',
    is_official: true,
    status: 'official',
  },

  // ── Cool / Modal ───────────────────────────────────────────────────────────
  {
    title: 'So What',
    composer: ['Miles Davis'],
    year_composed: 1959,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['cool', 'modal'],
    feel_tags: [],
    factoid: 'The opening track of "Kind of Blue," the most best-selling jazz album of all time. The two-chord modal structure — 16 bars of D dorian, 8 bars of Eb dorian, back to D — was radically simple compared to bebop\'s complexity.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Blue In Green',
    composer: ['Miles Davis', 'Bill Evans'],
    year_composed: 1959,
    original_key: 'G minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['cool', 'modal'],
    feel_tags: ['ballad'],
    factoid: 'The authorship of this haunting 10-bar piece has been disputed between Davis and Evans for decades — Evans claimed he wrote it, Davis took sole credit. The ambiguity seems fitting for a tune so dreamlike and hard to pin down.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Waltz For Debby',
    composer: ['Bill Evans'],
    year_composed: 1964,
    original_key: 'F major',
    time_signature: '3/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['cool', 'post-bop'],
    feel_tags: [],
    factoid: 'Originally written as a piano piece for his niece Debby, Evans later set it to the words of Gene Lees. The Village Vanguard live recording from June 1961 — recorded days before bassist Scott LaFaro\'s death — is considered a tragic masterpiece.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Nardis',
    composer: ['Miles Davis'],
    year_composed: 1958,
    original_key: 'E minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['cool', 'modal'],
    feel_tags: [],
    factoid: 'Davis wrote Nardis but rarely if ever played it himself — he gave it to Bill Evans, who made it a centerpiece of his repertoire for the rest of his life. Evans\'s meditative approach transformed it into something deeply personal.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'My Favorite Things',
    composer: ['Richard Rodgers'],
    year_composed: 1959,
    original_key: 'E minor',
    time_signature: '3/4',
    tempo_feel: 'variable',
    form: null,
    era_tags: ['great-american-songbook', 'post-bop'],
    feel_tags: ['straight-8ths'],
    factoid: 'From the musical "The Sound of Music," Coltrane turned this waltz into a modal journey by vamping on each chord for extended periods. His soprano saxophone version became his signature piece and one of the best-selling jazz singles ever.',
    is_official: true,
    status: 'official',
  },

  // ── Hard-Bop ───────────────────────────────────────────────────────────────
  {
    title: "Moanin'",
    composer: ['Bobby Timmons'],
    year_composed: 1958,
    original_key: 'F minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop'],
    feel_tags: ['funk'],
    factoid: 'The gospel and blues-inflected opening riff is one of the most recognizable in jazz. Art Blakey\'s recording with the Jazz Messengers became so popular that bassist Charles Mingus immediately recorded his own version with a new melody.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'The Sidewinder',
    composer: ['Lee Morgan'],
    year_composed: 1963,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop'],
    feel_tags: ['funk'],
    factoid: 'Morgan\'s funky Latin-tinged blues became Blue Note\'s best-selling album of the 1960s — even crossing over into mainstream radio play. The groove is built on a "cha cha" feel that bridged hard bop and the coming soul jazz movement.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Maiden Voyage',
    composer: ['Herbie Hancock'],
    year_composed: 1965,
    original_key: 'D major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'modal'],
    feel_tags: [],
    factoid: 'The album was conceived as a tone poem about the sea — each tune represents a nautical scene. The use of suspended chords throughout gives the entire record a floating, ambiguous quality that was new in jazz.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Cantaloupe Island',
    composer: ['Herbie Hancock'],
    year_composed: 1964,
    original_key: 'F minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'modal'],
    feel_tags: ['funk'],
    factoid: 'One of the most sampled jazz tracks in hip-hop history — US3\'s 1992 "Cantaloop (Flip Fantasia)" brought it to a new generation. The three-chord vamp structure makes it endlessly grooveable but deceptively difficult to play at a high level.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Dolphin Dance',
    composer: ['Herbie Hancock'],
    year_composed: 1965,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'modal'],
    feel_tags: [],
    factoid: 'From the "Maiden Voyage" album, this tune\'s constantly shifting tonal centers and lack of a clear key make it one of the most harmonically challenging standards in the modern jazz repertoire.',
    is_official: true,
    status: 'official',
  },

  // ── Post-Bop ───────────────────────────────────────────────────────────────
  {
    title: 'Giant Steps',
    composer: ['John Coltrane'],
    year_composed: 1959,
    original_key: 'B major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: [],
    factoid: 'The chord changes cycle through three tonal centers a major third apart (B, G, Eb), moving so fast at tempo that they\'re almost impossible to negotiate with conventional bebop vocabulary. The 1959 recording reportedly left Coltrane\'s peers stunned.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Naima',
    composer: ['John Coltrane'],
    year_composed: 1959,
    original_key: 'Ab major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['ballad'],
    factoid: 'Written for Coltrane\'s first wife, Juanita "Naima" Grubbs. The entire melody sits over a pedal tone in the bass — a static drone that gives the tune its meditative, devotional quality. One of the most beautiful ballads in jazz.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Impressions',
    composer: ['John Coltrane'],
    year_composed: 1963,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['hard-bop', 'post-bop', 'modal'],
    feel_tags: [],
    factoid: 'The same two-chord structure as Miles Davis\'s "So What" (D minor, Eb minor), but Coltrane\'s "sheets of sound" approach transforms it into something volcanic. The live recordings from the early \'60s document his most intense improvisations.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Footprints',
    composer: ['Wayne Shorter'],
    year_composed: 1966,
    original_key: 'C minor',
    time_signature: '6/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'Often played in 4/4 or 6/4, Shorter\'s minor blues-ish structure is deceptively simple. Miles Davis\'s version from "Miles Smiles" (1966) stripped it down to pure swing, while the original was more explicitly written in 6.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Speak No Evil',
    composer: ['Wayne Shorter'],
    year_composed: 1964,
    original_key: 'Eb minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'Shorter described this tune as being about "a witch\'s brew." The dark, minor tonality and chromatically dense melody embody a new approach to jazz composition that looked beyond bebop toward something more cinematic.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Infant Eyes',
    composer: ['Wayne Shorter'],
    year_composed: 1964,
    original_key: 'Db major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: ['ballad'],
    factoid: 'Shorter wrote this lullaby for his daughter. The melody\'s unusually long, floating phrases and ambiguous harmonic grounding make it sound like it exists outside of regular time — one of jazz\'s most ethereal ballads.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'E.S.P.',
    composer: ['Wayne Shorter'],
    year_composed: 1965,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'The title track from one of Miles Davis\'s greatest albums. Shorter\'s melody moves through a kaleidoscope of key centers in just 16 bars — a compact masterclass in motivic development and harmonic ambiguity.',
    is_official: true,
    status: 'official',
  },

  // ── Bossa Nova / Latin ──────────────────────────────────────────────────────
  {
    title: 'Wave',
    composer: ['Antônio Carlos Jobim'],
    year_composed: 1967,
    original_key: 'D major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['bossa-nova'],
    factoid: 'One of Jobim\'s most harmonically sophisticated tunes, "Wave" uses chromatic voice leading that rivals bebop\'s complexity while maintaining bossa nova\'s languid feel. The melody waves gently up and down like the ocean.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Desafinado',
    composer: ['Antônio Carlos Jobim', 'Newton Mendonça'],
    year_composed: 1959,
    original_key: 'F major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['bossa-nova'],
    factoid: '"Slightly Out of Tune" — the title is a joke about critics who said bossa nova singers were off-key. The melody intentionally includes a "wrong" note (a tritone) that beautifully resolves, making the point that dissonance can be beautiful.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'How Insensitive',
    composer: ['Antônio Carlos Jobim', 'Vinícius de Moraes'],
    year_composed: 1961,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['bossa-nova'],
    factoid: 'Originally "Insensatez" in Portuguese, the descending bass line against a static melody gives the tune its characteristic bittersweet feel. The original lyric reflects on the cruelty of a lover\'s coldness after a breakup.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Corcovado',
    composer: ['Antônio Carlos Jobim'],
    year_composed: 1960,
    original_key: 'D minor',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['bossa-nova', 'ballad'],
    factoid: 'Named for the mountain in Rio de Janeiro where the Christ the Redeemer statue stands, also known as "Quiet Nights of Quiet Stars." The Stan Getz/João Gilberto recording with Astrud Gilberto\'s vocal is definitive.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Black Orpheus',
    composer: ['Luiz Bonfá'],
    year_composed: 1959,
    original_key: 'A minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['bossa-nova', 'samba'],
    factoid: 'Also known as "Manhã de Carnaval" (Morning of Carnival), written for the Brazilian film "Orfeu Negro" (Black Orpheus). The film won the Palme d\'Or at Cannes and an Oscar for Best Foreign Film, bringing bossa nova to the world.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'One Note Samba',
    composer: ['Antônio Carlos Jobim', 'Newton Mendonça'],
    year_composed: 1961,
    original_key: 'Db major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['post-bop'],
    feel_tags: ['samba'],
    factoid: 'True to its name, the melody\'s first section is built almost entirely on one repeated pitch. The playful repetition and biting harmony underneath made it a jazz standard that rewards sophisticated improvisation.',
    is_official: true,
    status: 'official',
  },

  // ── Miscellaneous Post-Bop / Modern ─────────────────────────────────────────
  {
    title: 'Inner Urge',
    composer: ['Joe Henderson'],
    year_composed: 1965,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'Henderson\'s most harmonically complex original — the changes are so dense and far-ranging that McCoy Tyner initially refused to play it, reportedly saying he didn\'t know what to do with it. It remains one of the most challenging heads to navigate.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Recorda Me',
    composer: ['Joe Henderson'],
    year_composed: 1963,
    original_key: 'A minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop'],
    feel_tags: ['latin'],
    factoid: '"Remember Me" in Portuguese — Henderson\'s first composition to appear on a Blue Note recording. Its bossa-tinged Latin feel and minor tonality make it an approachable yet sophisticated vehicle for improvisation.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Witch Hunt',
    composer: ['Wayne Shorter'],
    year_composed: 1964,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'From the "Speak No Evil" album, this minor-key tune has a searching, paranoid quality. The changes move in unexpected directions that challenge improvisers to abandon familiar patterns and listen deeply.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'La Fiesta',
    composer: ['Chick Corea'],
    year_composed: 1972,
    original_key: 'A minor',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['post-bop', 'fusion'],
    feel_tags: ['latin', 'samba'],
    factoid: 'Written for Corea\'s Return to Forever group, this fiery Spanish-flavored tune draws on flamenco and samba. The intensity builds through an ascending series of key changes that creates a sense of joyous, unstoppable momentum.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Spain',
    composer: ['Chick Corea'],
    year_composed: 1972,
    original_key: 'A major',
    time_signature: '4/4',
    tempo_feel: 'variable',
    form: null,
    era_tags: ['post-bop', 'fusion'],
    feel_tags: ['latin'],
    factoid: 'The opening quote from Rodrigo\'s "Concerto de Aranjuez" leads into one of jazz-fusion\'s most beloved tunes. Corea wrote it in a single day, reportedly inspired by the classical concerto playing in the studio while he was composing.',
    is_official: true,
    status: 'official',
  },
  {
    title: "There Is No Greater Love",
    composer: ['Isham Jones'],
    year_composed: 1936,
    original_key: 'Bb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'A swinging medium-tempo standard that became a bebop and hard bop staple. The rhythm changes-adjacent harmony makes it an accessible but satisfying blowing vehicle, popular at jam sessions.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Softly As In A Morning Sunrise',
    composer: ['Sigmund Romberg'],
    year_composed: 1928,
    original_key: 'C minor',
    time_signature: '4/4',
    tempo_feel: 'variable',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From the operetta "The New Moon," this 16-bar tune alternates between minor for the melody and major for a bright, hopeful interlude. John Coltrane\'s "Live at the Village Vanguard" version at burning tempo is one of the most thrilling performances in jazz.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Moment\'s Notice',
    composer: ['John Coltrane'],
    year_composed: 1957,
    original_key: 'Db major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['hard-bop', 'post-bop'],
    feel_tags: [],
    factoid: 'Appearing on the "Blue Train" album, this tune\'s rapidly shifting ii-V-I progressions were Coltrane\'s early experiments with the harmonic density that would culminate in "Giant Steps" two years later.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Spring Can Really Hang You Up The Most',
    composer: ['Tommy Wolf'],
    year_composed: 1955,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'The lyrics by Fran Landesman describe the depression that spring can bring — the contrast between the season\'s renewal and personal stagnation. Ella Fitzgerald\'s recording is definitive but countless vocalists have made it their own.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'What Is This Thing Called Love',
    composer: ['Cole Porter'],
    year_composed: 1929,
    original_key: 'C major',
    time_signature: '4/4',
    tempo_feel: 'up-tempo',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'The bridge\'s abrupt move to a distant key was considered shocking in 1929. Charlie Parker rewrote it as "Hot House," one of the canonical bebop heads that appeared on the first recording ever labeled as bebop.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'But Not For Me',
    composer: ['George Gershwin'],
    year_composed: 1930,
    original_key: 'Eb major',
    time_signature: '4/4',
    tempo_feel: 'medium',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: [],
    factoid: 'From "Girl Crazy," the musical that launched both Ethel Merman and Ginger Rogers to fame. Chet Baker\'s heartbroken, understated vocal version perfectly captures the lyric\'s resigned bittersweet quality.',
    is_official: true,
    status: 'official',
  },
  {
    title: 'Embraceable You',
    composer: ['George Gershwin'],
    year_composed: 1930,
    original_key: 'G major',
    time_signature: '4/4',
    tempo_feel: 'ballad',
    form: null,
    era_tags: ['great-american-songbook'],
    feel_tags: ['ballad'],
    factoid: 'Charlie Parker recorded two different improvised versions on the same day in 1947, constructing entirely new melodies from the chord changes. These recordings are landmarks in jazz improvisation — he barely references the original melody.',
    is_official: true,
    status: 'official',
  },
]
